server:
  port: 9999
  session:
    timeout: 1800

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-mvc?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /page/
      
mybatis:
   mapper-locations: classpath:mappers/*.xml
   
logging:
  level:
    root: debug   